app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      #ssl: require # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
        #ca: # if you have a CA file and want to verify it you can uncomment this section
        #  $file: <file-path>/ca/server.crt
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  '/cost-insights-plugin':
    target: http://localhost:8080
    headers:
      Content-Type: 'application/json'
      Authorization:
        'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50SUQiOjF9.GsXyFDDARjXe1t9DPo2LIBKHEal3O7t3vLI3edA7dGU'
  '/test':
    target: 'https://example.com'
    changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers: {}

scaffolder:
  github:
    token: ${GITHUB_TOKEN}
    visibility: public # or 'internal' or 'private'

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    # Backstage example components
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

    # Backstage example systems
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-systems.yaml

    # Backstage example APIs
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml

    # Backstage example resources
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-resources.yaml

    # Backstage example organization groups
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/org.yaml

    # Backstage example templates
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/spotify/cookiecutter-golang/blob/master/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml
      rules:
        - allow: [Template]
costInsights:
  engineerCost: 200000
  products:
# Google Cloud Products
#    computeEngine:
#      name: Compute Engine
#      icon: compute
#    cloudDataflow:
#      name: Cloud Dataflow
#      icon: data
#    cloudStorage:
#      name: Cloud Storage
#      icon: storage
#    bigQuery:
#      name: BigQuery
#      icon: search
#    events:
#      name: Events
#      icon: data
    # AWS Services
    EC2:
      name: EC2
      icon: compute
    EC2Other:
      name: EC2-Other
      icon: data
    S3:
      name: S3
      icon: storage
    RDS:
      name: RDS
      icon: database
    DynamoDB:
      name: DynamoDB
      icon: database
    ElasticSearch:
      name: ElasticSearch
      icon: search
    CloudWatch:
      name: CloudWatch
      icon: data
    CloudTrail:
      name: CloudTrail
      icon: data
    ELB:
      name: ELB
      icon: compute
    EMR:
      name: EMR
      icon: ml
    MSK:
      name: Managed Kafka
      icon: data
    Lambda:
      name: Lambda
      icon: compute
    SQS:
      name: SQS
      icon: data
    SNS:
      name: SNS
      icon: data
  metrics:
    DAR:
      name: Daily Average Requests
      default: true
    DAC:
      name: Daily Active Clients
    BudgetTotal:
      name: Target Cost Total Budget
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: http://127.0.0.1:63867
          name: kind-kind
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IjVyVzEyOGhMVXMxQmJ0V19Fb1dJNXZiT0RzZ3dMRDg3VE53aTJfN0VRYVUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZC10b2tlbi14anBzdyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijg3NGFkYjNjLTY0MDctNDAzMS1hYmUxLTg5YmRlYzIzNGI2MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDprdWJlcm5ldGVzLWRhc2hib2FyZCJ9.gjPg1j1SS0fK8zolKO1jjIvxgSpyb5Cy9ikN5LoUy_mk98-Zzw06RRIg3SH2w4MEtM1cM_maWfF3hwbVWm269LvGX5AxXvu7remKGhN6yWq4i7kUoJS12CsqX2C4mRwwX68fWlMjU5z_HEtHUwc4f5BtOGGYYSnvJ9eVFBw_Z1Dt9QNY7_86FhjgFz-yBWBcg1LN2nW9QKhaodZP6kWZG6Eco0EhzOYUR_9dfVzGUsWRiaSwKWmDw6FAJ3bYesKdnGAJT94QozW1j-zOc_p1JdFk-Bbabz1oZ8VXdyThCglLedprnhv-eOnvGyziD6yQnq-886v7IpkZrU64DQIK4Q
#          dashboardUrl: http://127.0.0.1:4713 # for kind kubectl -n kubernetes-dashboard port-forward deploy/kubernetes-dashboard 4713:443
#          dashboardApp: standard
